# $modulepath/templated_file/manifests/init.pp
define templated_file (
  $template,
  $path                    = $title,
  $ensure                  = file,
  $backup                  = 'puppet',
  $checksum                = undef,
  $force                   = false,
  $group                   = undef,
  $ignore                  = undef,
  $links                   = 'manage',
  $mode                    = undef,
  $owner                   = undef,
  $provider                = undef,
  $purge                   = false,
  $replace                 = true,
  $selinux_ignore_defaults = undef,
  $selrange                = undef,
  $selrole                 = undef,
  $seltype                 = undef,
  $seluser                 = undef,
  $show_diff               = true,
  $sourceselect            = 'first',
  $validate_cmd            = undef,
  $validate_replacement    = '%',
) {
  file { $title:
    ensure                  => file,
    content                 => template($template),
    path                    => $title,
    backup                  => 'puppet',
    checksum                => undef,
    force                   => false,
    group                   => undef,
    ignore                  => undef,
    links                   => 'manage',
    mode                    => undef,
    owner                   => undef,
    provider                => undef,
    purge                   => false,
    replace                 => true,
    selinux_ignore_defaults => undef,
    selrange                => undef,
    selrole                 => undef,
    seltype                 => undef,
    seluser                 => undef,
    show_diff               => true,
    sourceselect            => 'first',
    validate_cmd            => undef,
    validate_replacement    => '%',
  }
}
